{% set version = "1.2.37" %}

package:
  name: libxmlsec1
  version: {{ version }}

source:
  url: https://www.aleksey.com/xmlsec/download/xmlsec1-{{ version }}.tar.gz
  sha256: 5f8dfbcb6d1e56bddd0b5ec2e00a3d0ca5342a9f57c24dffde5c796b2be2871c

build:
  number: 1
  # libgpg-error and libgcrypt aren't available on s390x
  skip: true  # [win or (linux and s390x)]
  run_exports:
    # compatibility is not tracked at abi-laboratory, assume same as libxml2
    - {{ pin_subpackage('libxmlsec1', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libtool
  host:
    - icu
    - libgcrypt 1.9.3
    - libgpg-error 1.42
    - libiconv 1.16  # [not linux]
    - libtool
    - libxml2 {{ libxml2 }}
    - libxslt 1.1.37
    - openssl {{ openssl }}
    - xz
    - zlib 1.2.13
  run:
    # libltdl is linked, which the libtool package provides.
    # This is needed to enable dynamic loading support for xmlsec-crypto
    # libraries (--enable-crypto-dl option).
    - {{ pin_compatible('libtool') }}
    - {{ pin_compatible('xz') }}
    - {{ pin_compatible('zlib') }}

test:
  requires:
    - ripgrep
  commands:
    - xmlsec1 --help
    - xmlsec1 --version | rg {{ version }}

about:
  home: https://www.aleksey.com/xmlsec/
  license: MIT and MPL-1.1
  license_family: Other
  license_file: Copyright
  summary: XML Security Library
  description: |
    XML Security Library is a C library based on LibXML2. 
    The library supports major XML security standards.
  dev_url: https://github.com/lsh123/xmlsec
  doc_url: https://www.aleksey.com/xmlsec/documentation.html
